apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app
  namespace: devops-lab
  labels:
    app: node-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - devops-lab.example.com
    secretName: node-app-tls
  rules:
  - host: devops-lab.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-app
            port:
              number: 80
