apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app
  namespace: devops-lab
  labels:
    app: node-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
