global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nodeapp'
    metrics_path: /metrics
    static_configs:
      - targets: ['nodeapp:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins:8080']
