apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-lab-chart.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "devops-lab-chart.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
