apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-lab-chart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "devops-lab-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "devops-lab-chart.selectorLabels" . | nindent 4 }}
